#macro BALL_SIZE 8
#macro BRICK_SIZE 6
#macro POWERUP_SIZE 16
#macro BALL_SPEED 7
#macro POWERUP_SPEED 3
#macro MAX_BALLS_FOR_TRIPLE power(3, 8)
#macro MAX_BALLS power(3, 9)
#macro MAX_COLLISION_DISTANCE 100000000